### ISSUE TITLE
Añadir métodos y tests realizados

### ISSUE THREAD

**Issue by mjls130598** [mjls130598/SharingNotes#37]

**Comment by JJ** [comment]
A ver, para ser puristas, este issue no sería correcto. El "bug" que quieres corregir es "No se ven los métodos y tests realizados en el README". No se trata de código, sin embargo, y en todo caso está bien que os abráis issues para resolver problemas, pero cuanto antes empecéis a seguir las buenas prácticas en todos los issues que se creen más automático será y no habrá que pararse mucho a  pensar
